export const COURSE_ADD_TO_CART = 'COURSE_ADD_TO_CART';
export const GET_KEYWORD ='GET_KEYWORD';
export const GET_LIST_COURSE ='GET_LIST_COURSE';
export const GET_LIST_CATEGORY ='GET_LIST_CATEGORY';
export const GET_LIST_COURSE_BY_CATEGORY='GET_LIST_COURSE_BY_CATEGORY';
export const INTO_PAGINATION='INTO_PAGINATION';
export const GET_DETAIL_COURSE='GET_DETAIL_COURSE';
