// export const COURSE_ADD_TO_CART = 'COURSE_ADD_TO_CART';
// export const GET_KEYWORD ='GET_KEYWORD';
// export const GET_LIST_COURSE ='GET_LIST_COURSE';
// export const GET_LIST_CATEGORY ='GET_LIST_CATEGORY';
// export const GET_LIST_COURSE_BY_CATEGORY='GET_LIST_COURSE_BY_CATEGORY';
// export const INTO_PAGINATION='INTO_PAGINATION';
// export const GET_DETAIL_COURSE='GET_DETAIL_COURSE';
// export const REGISTER_COURSE ='REGISTER_COURSE';
// export const CANCEL_REGISTER_COURSE ='CANCAL_REGISTER_COURSE';

export const COURSE_DETAIL_SUCCESS = "COURSE_DETAIL_SUCCESS";
export const COURSE_ADD_TO_CARD = "COURSE_ADD_TO_CARD";

export const REGISTER_COURSE_REQUEST =
  "REGISTER_COURSE_REQUEST";
export const REGISTER_COURSE_SUCCESS =
  "REGISTER_COURSE_SUCCESS";
export const REGISTER_COURSE_FAILED = "REGISTER_COURSE_FAILED";

export const COURSE_REQUEST = 'COURSE_REQUEST';
export const COURSE_FAILED = 'COURSE_FAILED';
export const COURSE_CATEGORY_SUCCESS = 'COURSE_CATEGORY_SUCCESS';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';

export const USER_SELECTOR_REQUEST = "USER_SELECTOR_REQUEST";
export const USER_SELECTOR_SUCCESS = "USER_SELECTOR_SUCCESS";
export const USER_SELECTOR_FAILED ="USER_SELECTOR_FAILED";

export const USER_WAITING_REQUEST = "USER_WAITING_REQUEST";
export const USER_WAITING_SUCCESS = "USER_WAITING_SUCCESS";
export const USER_WAITING_FAILED = "USER_WAITING_FAILED";


export const USER_JOINED_REQUEST = "USER_JOINED_REQUEST";
export const USER_JOINED_SUCCESS = "USER_JOINED_SUCCESS";
export const USER_JOINED_FAILED = "USER_JOINED_FAILED";


export const GET_CODECOURSE = "GET_CODECOURSE";


export const ADMIN_REGISTER_COURSE_REQUEST = "ADMIN_REGISTER_COURSE_REQUEST";
export const ADMIN_REGISTER_COURSE_SUCCESS = "ADMIN_REGISTER_COURSE_SUCCESS";
export const ADMIN_REGISTER_COURSE_FAILED = "ADMIN_REGISTER_COURSE_FAILED";

export const COURSE_DELETE = "COURSE_DELETE";
export const COURSE_ADD = "COURSE_ADD";
export const COURSE_UPDATE = "COURSE_UPDATE";