export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_REQUEST ='REGISTER_REQUEST';
export const REGISTER_SUCCESS ='REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
//GET USER PAGINATION
export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAILED = "USER_LIST_FAILED";

//GET USER INFO
export const GET_USERINFO_REQUEST = "GET_USERINFO_REQUEST";
export const GET_USERINFO_SUCCESS = "GET_USERINFO_SUCCESS";
export const GET_USERINFO_FAILED = "GET_USERINFO_FAILED";

//MODAL
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

//SUBMIT
export const ONSUBMIT_REQUEST = "ONSUBMIT_REQUEST";
export const ONSUBMIT_SUCCESS = "ONSUBMIT_SUCCESS";
export const ONSUBMIT_FAILED = "ONSUBMIT_FAILED";

//GET KEYWORD
export const GETKEYWORD = "GETKEYWORD";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILED = "USER_PROFILE_FAILED";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

export const CANCEL_COURSE_REQUEST = "CANCEL_COURSE_REQUEST";
export const CANCEL_COURSE_SUCCESS = "CANCEL_COURSE_SUCCESS";
export const CANCEL_COURSE_FAILED = "CANCEL_COURSE_FAILED";

